// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQFIHa4fW2nHymi4AtkNDud9R-GyjIpQ8',
    appId: '1:158274912054:web:05f950a8d96907385dfd97',
    messagingSenderId: '158274912054',
    projectId: 'home-mate-a7f7e',
    authDomain: 'home-mate-a7f7e.firebaseapp.com',
    storageBucket: 'home-mate-a7f7e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDlP2Qz_Zkv6FgBUGZPzv2qVID-0VeDOE',
    appId: '1:158274912054:android:793559bd1369b6625dfd97',
    messagingSenderId: '158274912054',
    projectId: 'home-mate-a7f7e',
    storageBucket: 'home-mate-a7f7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZTFsVzVKbtsH05b4HkzlNkU2qvoMsOy0',
    appId: '1:158274912054:ios:9367d2a5a6163f785dfd97',
    messagingSenderId: '158274912054',
    projectId: 'home-mate-a7f7e',
    storageBucket: 'home-mate-a7f7e.appspot.com',
    androidClientId: '158274912054-ue7luh9sksusn19gepvuqqthvm5e56ul.apps.googleusercontent.com',
    iosClientId: '158274912054-6ac285at7kpou80no6rqt9ku4khh8p0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZTFsVzVKbtsH05b4HkzlNkU2qvoMsOy0',
    appId: '1:158274912054:ios:be774bad4bf0d6255dfd97',
    messagingSenderId: '158274912054',
    projectId: 'home-mate-a7f7e',
    storageBucket: 'home-mate-a7f7e.appspot.com',
    androidClientId: '158274912054-ue7luh9sksusn19gepvuqqthvm5e56ul.apps.googleusercontent.com',
    iosClientId: '158274912054-ib391k0besomnlm3ii0afsg57hoc51qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeMate.RunnerTests',
  );
}
